### ISSUE TITLE
System.NullReferenceException for GetCampaignsAsync()

### ISSUE THREAD

**Issue by DurtyFree** [sawch/Patreon.Net#9]
I think Patreon changed something for their API, seems like its throwing this exception since some days/weeks (not sure)

![grafik](https://user-images.githubusercontent.com/20757266/184557241-5ada695e-69db-4e38-a911-6d3ea8e7eea8.png)

**Comment by DurtyFree** [comment]
Nevermind, I debugged further with the source code and its just the API endpoint returning 401 Unauthorized due to an expired access token it seems.

Maybe this should be catched and a more useful exception should be thrown

**Comment by sawch** [comment]
Thanks for reporting this! Should be fixed now.
